---

- name: Clone oh-my-zsh git repository to user's home folder
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
    update: true
  with_items: "{{ ohmyzsh_users }}"
  tags:
    - ohmyzsh

- name: Clone zsh-autosuggestions plugin git repo
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
    depth: 1
    update: true
  with_items: "{{ ohmyzsh_users }}"
  tags:
    - plugins

- name: Clone autoupdate-zsh-plugin
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
    dest: ~/.oh-my-zsh/plugins/autoupdate
    depth: 1
    update: true
  with_items: "{{ ohmyzsh_users }}"
  tags:
    - plugins

- name: Clone the powerlevel10k theme
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/themes/powerlevel10k
    depth: 1
    update: true
  with_items: "{{ ohmyzsh_users }}"
  tags:
    - plugins

- name: Copy .zshrc template to user's home folder
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: zshrc.j2
    dest: ~/.zshrc
    backup: true
    mode: "0775"
  with_items: "{{ ohmyzsh_users }}"
  tags:
    - config

- name: Copy .p10k.zsh template to user's home folder
  become: true
  become_user: "{{ item }}"
  ansible.builtin.copy:
    src: p10k.zsh
    dest: ~/.p10k.zsh
    backup: true
    mode: "0775"
  with_items: "{{ ohmyzsh_users }}"
  tags:
    - config

- name: Change default shell to zsh for users
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ ohmyzsh_zsh_path }}"
  with_items: "{{ ohmyzsh_users }}"
  when: ohmyzsh_chsh
  tags:
    - shell
